mqtt:
  hostname: ${MQTTHOST}
  port: ${MQTTPORT} #defaults to 1883
  user: ${MQTTUSER}
  password: ${MQTTPASS}
  discovery: true
  discovery_prefix: homeassistant
deviceName: ${MQTTHOST}
client_id: ${CLIENTID}
timezone: ${TIMEZONE}
update_interval: 60 #Defaults to 60
sensors:
  temperature: true
  display: true
  clock_speed: true
  disk_use: true
  memory_use: true
  cpu_usage: true
  load_1m: true
  load_5m: true
  load_15m: true
  net_tx: true
  net_rx: true
  swap_usage: true
  power_status: true
  last_boot: true
  uptime: true
  hostname: true
  host_ip: true
  host_os: true
  host_arch: true
  last_message: true
  updates: true
  wifi_strength: true
  wifi_ssid: true
  external_drives:
    # Only add mounted drives here, e.g.:
    # Drive1: /media/storage
    # For ZFS Pools use the format:
    # pool-name: /mount-point
